export function buildNaverApiTokenFirstTestReadOnlyPhaseClosureSummaryView() {
  return {
    screenTitle: 'Token First Test Phase Closure Summary',
    phaseName: 'Read-only Safety Review Phase',
    phaseStatus: 'COMPLETED',
    reviewedFlowCount: 19, // Task 41~59 (approx)
    auditTargetCommit: 'b157e26',
    auditResultCommit: 'c67ea14',
    allScreensReadOnly: true,
    executionStillForbidden: true,
    tokenRequestStillForbidden: true,
    naverApiCallStillForbidden: true,
    operatingDbWriteStillForbidden: true,
    priceStockChangeStillForbidden: true,
    queueWorkerStillDisconnected: true,
    postApiStillNotAdded: true,
    task58BulkAddAuditCompleted: true,
    nextStepLabel: '별도 승인 기준 검토 단계로 이관 (즉시 실행 아님)',
    closureSummaryItems: [
      {
        id: 1,
        label: '안전 검토 단계 종료 여부',
        value: '종료 완료 (Read-only Phase Closed)',
        isReadOnly: true,
      },
      {
        id: 2,
        label: '실제 토큰 발급 여부',
        value: '발급 이력 없음 (요청 차단됨)',
        isReadOnly: true,
      },
      {
        id: 3,
        label: '실제 Naver API 연동 여부',
        value: '연동 이력 없음 (호출 차단됨)',
        isReadOnly: true,
      },
      {
        id: 4,
        label: '실제 DB Write 반영 여부',
        value: '반영 이력 없음 (Mutation 차단됨)',
        isReadOnly: true,
      },
    ],
    stillForbiddenItems: [
      {
        id: 1,
        label: '실행 버튼 렌더링',
        value: 'FORBIDDEN',
        isReadOnly: true,
      },
      {
        id: 2,
        label: '승인 요청 제출',
        value: 'FORBIDDEN',
        isReadOnly: true,
      },
      {
        id: 3,
        label: 'POST API 호춣',
        value: 'FORBIDDEN',
        isReadOnly: true,
      },
      {
        id: 4,
        label: 'Token Request Execution',
        value: 'FORBIDDEN',
        isReadOnly: true,
      },
    ],
    completedPhaseItems: [
      {
        id: 1,
        label: 'Readiness Screen Flow',
        value: 'COMPLETED',
        isReadOnly: true,
      },
      {
        id: 2,
        label: 'Final Confirmation Gate Flow',
        value: 'COMPLETED',
        isReadOnly: true,
      },
      {
        id: 3,
        label: 'Action Lock Flow',
        value: 'COMPLETED',
        isReadOnly: true,
      },
      {
        id: 4,
        label: 'Safety Review Flow',
        value: 'COMPLETED',
        isReadOnly: true,
      },
      {
        id: 5,
        label: 'Safe Next Step Guide Flow',
        value: 'COMPLETED',
        isReadOnly: true,
      },
      {
        id: 6,
        label: 'Separate Approval Packet Flow',
        value: 'COMPLETED',
        isReadOnly: true,
      },
      {
        id: 7,
        label: 'Approval Evidence Timeline Flow',
        value: 'COMPLETED',
        isReadOnly: true,
      },
      {
        id: 8,
        label: 'Approval Console Flow',
        value: 'COMPLETED',
        isReadOnly: true,
      },
      {
        id: 9,
        label: 'Review Hub Navigation Flow',
        value: 'COMPLETED',
        isReadOnly: true,
      },
      {
        id: 10,
        label: 'Review Section Layout Flow',
        value: 'COMPLETED',
        isReadOnly: true,
      },
      {
        id: 11,
        label: 'Separate Approval Request Draft Flow',
        value: 'COMPLETED',
        isReadOnly: true,
      },
      {
        id: 12,
        label: 'Approval Readiness Checklist Flow',
        value: 'COMPLETED',
        isReadOnly: true,
      },
      {
        id: 13,
        label: 'Approval Decision Summary Flow',
        value: 'COMPLETED',
        isReadOnly: true,
      },
      {
        id: 14,
        label: 'Separate Approval Boundary Flow',
        value: 'COMPLETED',
        isReadOnly: true,
      },
      {
        id: 15,
        label: 'Approval Handoff Summary Flow',
        value: 'COMPLETED',
        isReadOnly: true,
      },
      {
        id: 16,
        label: 'Approval Handoff Verification Flow',
        value: 'COMPLETED',
        isReadOnly: true,
      },
      {
        id: 17,
        label: 'Manual Approval Checklist Alignment Flow',
        value: 'COMPLETED',
        isReadOnly: true,
      },
      {
        id: 18,
        label: 'Manual Approval Final Seal Flow',
        value: 'COMPLETED',
        isReadOnly: true,
      },
      {
        id: 19,
        label: 'Post Task 58 Commit Scope Audit',
        value: 'COMPLETED',
        isReadOnly: true,
      },
    ],
    // Safety Flags
    readOnlyPhaseClosureSummaryCreated: true,
    displayOnly: true,
    readOnly: true,
    executionLocked: true,
    manualReviewRequired: true,
    requiresSeparateLiveApproval: true,
    tokenTestStillNotAllowed: true,
    executionButtonRendered: false,
    executionButtonEnabled: false,
    approvalButtonRendered: false,
    approvalButtonEnabled: false,
    approvalRequestSubmitButtonRendered: false,
    approvalRequestSubmitButtonEnabled: false,
    checklistSaveButtonRendered: false,
    checklistSaveButtonEnabled: false,
    decisionSaveButtonRendered: false,
    decisionSaveButtonEnabled: false,
    boundaryReleaseButtonRendered: false,
    boundaryReleaseButtonEnabled: false,
    handoffSaveButtonRendered: false,
    handoffSaveButtonEnabled: false,
    handoffCopyButtonRendered: false,
    handoffCopyButtonEnabled: false,
    handoffSendButtonRendered: false,
    handoffSendButtonEnabled: false,
    verificationSaveButtonRendered: false,
    verificationSaveButtonEnabled: false,
    verificationConfirmButtonRendered: false,
    verificationConfirmButtonEnabled: false,
    finalSealSaveButtonRendered: false,
    finalSealSaveButtonEnabled: false,
    finalSealConfirmButtonRendered: false,
    finalSealConfirmButtonEnabled: false,
    finalSealReleaseButtonRendered: false,
    finalSealReleaseButtonEnabled: false,
    closureSaveButtonRendered: false,
    closureSaveButtonEnabled: false,
    closureConfirmButtonRendered: false,
    closureConfirmButtonEnabled: false,
    closureReleaseButtonRendered: false,
    closureReleaseButtonEnabled: false,
    formRendered: false,
    formSubmitEnabled: false,
    postApiEnabled: false,
    finalConfirmationPersisted: false,
    finalConfirmationDbWriteExecuted: false,
    finalConfirmationActionEnabled: false,
    liveTokenTestApproved: false,
    liveTokenTestExecutionAllowed: false,
    dbWriteAllowed: false,
    persistenceExecuted: false,
    metadataPersisted: false,
    auditEventPersisted: false,
    dbWriteExecuted: false,
    prismaMutationExecuted: false,
    goTicketIssued: false,
    executionLeaseIssued: false,
    sandboxInvocationAllowed: false,
    sandboxInvocationExecuted: false,
    coordinatorExecutionAllowed: false,
    requestPayloadCreated: false,
    requestBodyCreated: false,
    requestHeadersCreated: false,
    networkKillSwitchOpen: false,
    networkAdapterEnabled: false,
    networkExecutionAllowed: false,
    tokenNetworkRequestAllowed: false,
    tokenRequestAllowed: false,
    tokenRequestPrepared: false,
    tokenRequestExecuted: false,
    accessTokenRequested: false,
    refreshTokenRequested: false,
    credentialsUsed: false,
    clientSecretUsed: false,
    clientSecretSignCreated: false,
    tokenIssued: false,
    tokenStored: false,
    authorizationHeaderCreated: false,
    endpointResolved: false,
    endpointCalled: false,
    httpRequestCreated: false,
    httpClientCreated: false,
    naverApiCallAllowed: false,
    liveExecutionEnabled: false,
    queueAllowed: false,
    workerAllowed: false,
  };
}
